spreadsheet_id: "1WH_lkDhQVe2lj3l3uBHByM2mymeMbk1z1qUS8uMAy04"
semester_tag:
    alias: fall26
    name: Fall 2026
    type: semester
targets:
    - sheet_name: "Ru BS2"
    - sheet_name: "EN BS3"
    - sheet_name: "Ru BS3"
save_ics_path: fall26/electives
save_json_path: fall26/electives.json
electives: [

        # Ru BS2

        {
            "alias": "ФА",
            "short_name": "ФА",
            "name": "Функциональный анализ",
            "instructor": "Paul Ostanin",
        },
        {
            "alias": "АКМ",
            "short_name": "АКМ",
            "name": "Аналитические и компьютерные модели",
            "instructor": "Владимир Гордин",
        },
        {
            "alias": "DevOps",
            "short_name": "DevOps",
            "name": "DevOps",
            "instructor": "Ростелеком",
        },
        {
            "alias": "LCNC",
            "short_name": "LCNC",
            "name": "Low-code / No-code",
            "instructor": "Ростелеком",
        },
        {
            "alias": "ПИ",
            "short_name": "ПИ",
            "name": "Программная инженерия",
            "instructor": "Ростелеком",
        },
        {
            "alias": "СМУР",
            "short_name": "СМУР",
            "name": "Современные методы управления роботами",
            "instructor": "Сергей Савин",
        },

        # EN BS3

        {
            "alias": "IDORS",
            "short_name": "IDORS",
            "name": "Industrial development, operation and reliability of software systems",
            "instructor": "T-Bank team",
        },
        {
            "alias": "AEML",
            "short_name": "AEML",
            "name": "Introduction to Adaptive and Efficient Machine Learning",
            "instructor": "Akdodshoev Ahmadsho",
        },
        {
            "alias": "SD",
            "short_name": "SD",
            "name": "Security for Developers: Code, Data, Peopl",
            "instructor": "ООО \"СКАЕНГ\"",
        },
        {
            "alias": "DSO",
            "short_name": "DSO",
            "name": "Introduction to DevSecOps",
            "instructor": "Dmitry Creed",
        },
        {
            "alias": "SPDA",
            "short_name": "SPDA",
            "name": "Software Product Development and Analysis",
            "instructor": "Konstantin Arkhipov",
        },
        {
            "alias": "ISDP",
            "short_name": "ISDP",
            "name": "Industrial Software Development in Python: Key Technologies and Approaches",
            "instructor": "German Tarasov",
        },
        {
            "alias": "ISRE",
            "short_name": "ISRE",
            "name": "Introduction to SRE",
            "instructor": "Dmitry Creed",
        },
        {
            "alias": "OSINT",
            "short_name": "OSINT",
            "name": "Open Source Intelligence (OSINT)",
            "instructor": "Ростелеком",
        },
        {
            "alias": "BDA",
            "short_name": "BDA",
            "name": "Big Data Analytics",
            "instructor": "Ростелеком",
        },
        {
            "alias": "BSOC",
            "short_name": "BSOC",
            "name": "Building Security Operations Centers (SOC)",
            "instructor": "Ростелеком",
        },
        {
            "alias": "IDMG",
            "short_name": "IDMG",
            "name": "Intro to Development of Multiplayer Games",
            "instructor": "ООО \"Кар Икс Технолоджис\"",
        },
        {
            "alias": "PBP",
            "short_name": "PBP",
            "name": "Postal Business Portal: How a Digital B2B Product Is Built and Evolves",
            "instructor": "ООО \"Почтовые технологии\"",
        },
        {
            "alias": "DO",
            "short_name": "DO",
            "name": "Introduction to DevOps",
            "instructor": "Dmitry Creed",
        },
        {
            "alias": "BDJ",
            "short_name": "BDJ",
            "name": "Basics of Backend Development in Java",
            "instructor": "T-Bank team",
        },
        {
            "alias": "IITS",
            "short_name": "IITS",
            "name": "Industrial IT Systems: From Idea to Operation",
            "instructor": "ООО \"Почтовые технологии\"",
        },

        # EN BS3

        {
            "alias": "ВКЗ",
            "short_name": "ВКЗ",
            "name": "Введение в компьютерное зрение",
            "instructor": "Илья Афанасьев",
        },
        {
            "alias": "ВВРК",
            "short_name": "ВВРК",
            "name": "Введение в развитие карьеры ИТ-специалиста",
            "instructor": "Gulnaz Ibragimova",
        },
        {
            "alias": "ПИТС",
            "short_name": "ПИТС",
            "name": "Психология ИТ-специалиста",
            "instructor": "Alia Islamova",
        },
        {
            "alias": "ПВВБ",
            "short_name": "ПВВБ",
            "name": "Публичные выступления в бизнесе",
            "instructor": "Rakhmatullina Elena",
        },
    ]
