spreadsheet_id: 1qetU56NwowMgHSD4ZBSFDO5omeO6FHPYSIz6sde86yo
semester_tag:
  alias: sum26
  name: Sum 2026
  type: semester
targets:
  - sheet_name: SUMMER
    start_date: "2026-06-01"
    end_date: "2026-08-02"
save_ics_path: sum26/core-courses
save_json_path: sum26/core-courses.json
