name: "Parse schedules 🕵️‍♂️"
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  check:
    if: false
    name: "Parse schedules 🕵️‍"
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository 🚚"
        uses: actions/checkout@v4
      - name: "Pull the latest changes 🔄"
        run: git pull
      - name: "Set up uv 🚀"
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: false
          activate-environment: true
      - name: "Parse schedules 🕵️‍♂️"
        env:
          PARSER_AUTH_KEY: ${{ secrets.PARSER_AUTH_KEY }}
          INNOHASSLE_API_URL: "https://api.innohassle.ru/events/v0"
        run: uv run -m src
